name: Build and Deploy

on:
  push:
    branches:
      - master
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Deploy to Web Server
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USERNAME }}
          key: ${{ secrets.SERVER_KEY }}
          passphrase: ${{ secrets.SERVER_PASSPHRASE }}
          port: 22
          script: |
            cd /home/alpha/alph-admin
            git pull https://${{ secrets.SERVER_GIT_USERNAME }}:${{ secrets.SERVER_TOKEN }}@github.com/AxraTech/alpha-admin.git
            pm2 start ecosystem.config.js
